# Run a number of quality checks ever time a PR is opened
name: Pull Request Quality Checks

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Reason for manual trigger'
        required: true
        default: 'Re-run past failed build'

  pull_request:
    types: [opened, synchronize]

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
      # ref: https://github.com/marketplace/actions/checkout
      - name: Checkout code
        uses: actions/checkout@v4

      # ref: https://github.com/marketplace/actions/setup-node-js-environment
      - name: Install NodeJS
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'

      - name: Install dependencies
        run: npm ci --ignore-scripts
        env:
          CI: true

      # we need to cache these dependencies so it can be used in the parallel jobs below
      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: |
            ./*
            ~/.npm
          key: ${{ github.sha }}

  unit-testing:
    name: Unit testing
    runs-on: ubuntu-latest
    needs: setup
    steps:
      # restore dependencies that were installed in the `setup` job
      - name: Restore dependencies
        uses: actions/cache@v3
        with:
          path: |
            ./*
            ~/.npm
          key: ${{ github.sha }}

      - name: Testing
        run: npm test
        env:
          CI: true
          NODE_ENV: test
